# Generated by Django 6.0.6 on 2026-06-10 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="First day of the reported month"),
                ),
                ("pdf_file", models.FileField(upload_to="reports/")),
                ("total_complaints", models.IntegerField()),
                ("hotspot_count", models.IntegerField()),
                ("resolution_rate", models.FloatField(help_text="Percentage 0–100")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
    ]
