# Generated by Django 6.0.6 on 2026-06-11 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_citizenmessage_complaint_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("secondary_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("area", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="complaint",
            name="reporter_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
